name: Lint duckbug-js SDK
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version-file: ".nvmrc"
      - run: yarn install --frozen-lockfile # optional, --immutable
      - run: yarn lint
